{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar\",\"Customer Lookup\",\"Employee Lookup\",\"Food Inventory\",\"Product Lookup\",\"Sales by Store\",\"Store Lookup\",\"Measures Table\",\"DataSourceRoot\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DataSourceRoot",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"C:\\Users\\Giuseppe Rosa\\Documents\\Estudos\\dax-studies\\raw_data\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a05d7e29-4ce7-4beb-8b17-d37499561b80"
      }
    ],
    "relationships": [
      {
        "name": "a12aecc7-f320-53db-5248-ec7ddebc1203",
        "fromColumn": "transaction_date",
        "fromTable": "Sales by Store",
        "toColumn": "Transaction_Date",
        "toTable": "Calendar"
      },
      {
        "name": "94ce68fd-3ed5-72b1-e279-6af25f879956",
        "fromColumn": "transaction_date",
        "fromTable": "Food Inventory",
        "toColumn": "Transaction_Date",
        "toTable": "Calendar"
      },
      {
        "name": "af0dfc59-a919-214f-a1ee-c1ffe0e49532",
        "fromColumn": "customer_id",
        "fromTable": "Sales by Store",
        "toColumn": "customer_id",
        "toTable": "Customer Lookup"
      },
      {
        "name": "7647646e-dd93-61e5-20e3-07e4f0ef8644",
        "fromColumn": "product_id",
        "fromTable": "Sales by Store",
        "toColumn": "product_id",
        "toTable": "Product Lookup"
      },
      {
        "name": "923aa734-7828-00bd-92bb-fe7fc2bc072c",
        "fromColumn": "product_id",
        "fromTable": "Food Inventory",
        "toColumn": "product_id",
        "toTable": "Product Lookup"
      },
      {
        "name": "9185994c-2f65-4bb4-d8c7-9731fb786dc8",
        "fromColumn": "staff_id",
        "fromTable": "Sales by Store",
        "toColumn": "staff_id",
        "toTable": "Employee Lookup"
      },
      {
        "name": "fe6fafa7-8e71-fb5b-ffc3-730185ac599e",
        "fromColumn": "store_id",
        "fromTable": "Sales by Store",
        "toColumn": "store_id",
        "toTable": "Store Lookup"
      },
      {
        "name": "ef8d88e9-31d1-b28b-e5a0-d67cedd2c9af",
        "fromColumn": "store_id",
        "fromTable": "Food Inventory",
        "toColumn": "store_id",
        "toTable": "Store Lookup"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Transaction_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "isKey": true,
            "lineageTag": "f7110f6f-a62d-4751-9fb4-aeb64ef7eae2",
            "sourceColumn": "Transaction_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Date_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7da593f9-0461-450c-8dee-1e1f35b9c206",
            "sourceColumn": "Date_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "29e377c9-7d79-4aa8-905e-0935ee547256",
            "sourceColumn": "Week_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd6cf0f5-2d50-406b-a311-2fad0d82d983",
            "sourceColumn": "Week_Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Month_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd5a75c4-de34-4264-96ee-d2fd8f4672ca",
            "sourceColumn": "Month_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5115148c-593d-4d18-b626-2617597e2ac2",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c045aa9c-4bf9-4566-9783-1de476370485",
            "sourceColumn": "Quarter_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Quarter_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1b665ac-8c57-4d6e-ae85-2709be72925a",
            "sourceColumn": "Quarter_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f88b64c6-34f9-4289-8bd3-c72db79f1bad",
            "sourceColumn": "Year_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Week_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec66465b-731a-4a1b-8e8e-7331aff488dc",
            "sourceColumn": "Week_Year",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_date (yyyy-mm-dd)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(",
              "    'Calendar'[Transaction_Date],",
              "    \"yyyy-mm-dd\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "505741be-4585-48c5-affb-e81d9ac149a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year Half",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Calendar'[Month_ID],",
              "    1, \"1H\",",
              "    2, \"1H\",",
              "    3, \"1H\",",
              "    4, \"1H\",",
              "    5, \"1H\",",
              "    6, \"1H\",",
              "    7, \"2H\",",
              "    8, \"2H\",",
              "    9, \"2H\",",
              "    10, \"2H\",",
              "    11, \"2H\",",
              "    12, \"2H\",",
              "    \"-\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "43cd9694-f3b3-48a7-ba64-47f072317203",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter Formatted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Calendar'[Quarter_Name] & \"-\" & 'Calendar'[Year_ID]",
            "isDataTypeInferred": true,
            "lineageTag": "4ce2d7f1-75a5-4c74-8943-a3a8dce4c2f7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "93cf9639-54bb-441e-8ff6-984a7a700f4c",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Calendar.csv\"),[Delimiter=\",\", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Transaction_Date\", type date}, {\"Date_ID\", Int64.Type}, {\"Week_ID\", Int64.Type}, {\"Week_Desc\", type text}, {\"Month_ID\", Int64.Type}, {\"Month_Name\", type text}, {\"Quarter_ID\", Int64.Type}, {\"Quarter_Name\", type text}, {\"Year_ID\", Int64.Type}, {\"Week_Year\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "04d3a25b-f612-48d0-b31c-f63d51553e89",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "home_store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f22649e-5eca-4e7d-a2b7-4b3eae1abf89",
            "sourceColumn": "home_store",
            "summarizeBy": "none"
          },
          {
            "name": "customer_first-name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "735cd009-f362-4079-88b0-1e53fa2c1e5f",
            "sourceColumn": "customer_first-name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b2d733f-3648-4d04-85be-56fcf0e282ce",
            "sourceColumn": "customer_email",
            "summarizeBy": "none"
          },
          {
            "name": "customer_since",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c8f40212-d69c-4496-842c-7db246329d93",
            "sourceColumn": "customer_since",
            "summarizeBy": "none"
          },
          {
            "name": "loyalty_card_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0b95211-9558-4ee7-892c-0cafc332016d",
            "sourceColumn": "loyalty_card_number",
            "summarizeBy": "none"
          },
          {
            "name": "birthdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f4507165-20dc-4933-84a5-a94c89c38a77",
            "sourceColumn": "birthdate",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84c4be1b-aba6-49af-9a00-f6f7d7a17d8e",
            "sourceColumn": "gender",
            "summarizeBy": "none"
          },
          {
            "name": "birth_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da7d767f-625c-4c29-abac-0d7068ebf6fc",
            "sourceColumn": "birth_year",
            "summarizeBy": "none"
          },
          {
            "name": "Current Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "DATEDIFF(",
              "    'Customer Lookup'[birthdate], ",
              "    UTCNOW(),",
              "    YEAR)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "579cedda-0697-4549-b576-3a6e9dbb12f6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "355438b5-291c-44ed-9ca4-685e00829ab1",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Customer Lookup.csv\"),[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"home_store\", Int64.Type}, {\"customer_first-name\", type text}, {\"customer_email\", type text}, {\"customer_since\", type date}, {\"loyalty_card_number\", type text}, {\"birthdate\", type date}, {\"gender\", type text}, {\"birth_year\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "e62d8c75-aa85-4fe3-af44-60a730d13412",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "first_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3f19ffe-7d15-4b38-a64e-8cc3b4c3bb1f",
            "sourceColumn": "first_name",
            "summarizeBy": "none"
          },
          {
            "name": "last_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e45abae4-4858-4375-808c-f05a5e8bfdf3",
            "sourceColumn": "last_name",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ccaef00-44d1-4a6d-bb2c-20a304a8c6d4",
            "sourceColumn": "position",
            "summarizeBy": "none"
          },
          {
            "name": "start_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7b26b9cc-a667-49e3-8fac-3fa55289f670",
            "sourceColumn": "start_date",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "876c71cb-0f13-4af7-9cf3-a2250063ca88",
            "sourceColumn": "location",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3df49bda-9e6a-4be3-80eb-7c40de5d67d3",
        "partitions": [
          {
            "name": "Employee Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Employee Lookup.csv\"),[Delimiter=\",\", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"staff_id\", Int64.Type}, {\"first_name\", type text}, {\"last_name\", type text}, {\"position\", type text}, {\"start_date\", type date}, {\"location\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Food Inventory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc415708-95d0-4ead-b638-bcaff45c6a23",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "baked_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "16be5c30-8cba-4939-a2c9-e1050d37a3f3",
            "sourceColumn": "baked_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bf4912f1-5dca-4a68-9611-b51d63e2dd60",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3cec197a-8618-4c65-81db-d53608fb14d6",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_start_of_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4eac2a49-3e7b-4c92-88a0-44cf4e20dd56",
            "sourceColumn": "quantity_start_of_day",
            "summarizeBy": "sum"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "755ed061-b554-41e7-9295-e897ff9f8d17",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Sold (SUM)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SUM(",
              "    'Food Inventory'[quantity_sold]",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "a0ad0355-e1c1-431d-9385-bcda31b33ae5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quantity Sold (Calculate)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              " CALCULATE(",
              "    SUM(",
              "        'Food Inventory'[quantity_sold]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "a78a069b-3ee0-4457-9ca1-3582ce9f778e",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "fe650e26-b166-4651-8dc4-dfe7a425020e",
        "measures": [
          {
            "name": "Calculate Quantity Sold",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(",
              "    'Food Inventory'[quantity_sold]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3b43fffc-a569-4288-9f60-288a1dd6eeb9"
          }
        ],
        "partitions": [
          {
            "name": "Food Inventory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Food Inventory.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"baked_date\", type date}, {\"transaction_date\", type date}, {\"product_id\", Int64.Type}, {\"quantity_start_of_day\", Int64.Type}, {\"quantity_sold\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "ed9fe428-c8f3-49d0-be65-a4102b94011b",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5ae38f0-611f-4c2f-8edf-418d4badaad8",
            "sourceColumn": "product_group",
            "summarizeBy": "none"
          },
          {
            "name": "product_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc37d0ba-c014-46a5-a097-4c047ab96e17",
            "sourceColumn": "product_category",
            "summarizeBy": "none"
          },
          {
            "name": "product_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a31f9b8e-bf0d-47df-861a-1b291ad0cacb",
            "sourceColumn": "product_type",
            "summarizeBy": "none"
          },
          {
            "name": "product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e855e3c-c7a0-4be4-ace1-a20068e77bcb",
            "sourceColumn": "product",
            "summarizeBy": "none"
          },
          {
            "name": "product_description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28666e91-dbf5-4078-b0eb-f26925e75378",
            "sourceColumn": "product_description",
            "summarizeBy": "none"
          },
          {
            "name": "unit_of_measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de1c0c05-6741-4696-b4da-4e20084e8b3c",
            "sourceColumn": "unit_of_measure",
            "summarizeBy": "none"
          },
          {
            "name": "current_cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8c8c02c-047a-4165-b027-e84c1ab1cc84",
            "sourceColumn": "current_cost",
            "summarizeBy": "sum"
          },
          {
            "name": "current_wholesale_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4c0a86e0-bc39-478c-9302-49358f39f513",
            "sourceColumn": "current_wholesale_price",
            "summarizeBy": "sum"
          },
          {
            "name": "current_retail_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e61ac5dd-07e3-458d-9330-5a31d835e14b",
            "sourceColumn": "current_retail_price",
            "summarizeBy": "sum"
          },
          {
            "name": "tax_exempt_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c3bb5b3-1fd9-4025-994d-b1e1c812fb7f",
            "sourceColumn": "tax_exempt_yn",
            "summarizeBy": "none"
          },
          {
            "name": "promo_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5a660f0-0c46-4e0e-add2-4b5bb20105ff",
            "sourceColumn": "promo_yn",
            "summarizeBy": "none"
          },
          {
            "name": "new_product_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37231d50-e663-4f9e-8160-aac168a4896a",
            "sourceColumn": "new_product_yn",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a915dff0-de7a-42c4-b1c4-2fb0dc9cb36a",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Product Lookup (Updated).csv\"),[Delimiter=\",\", Columns=14, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"product_id\", Int64.Type}, {\"product_group\", type text}, {\"product_category\", type text}, {\"product_type\", type text}, {\"product\", type text}, {\"product_description\", type text}, {\"unit_of_measure\", type text}, {\"current_cost\", type number}, {\"current_wholesale_price\", type number}, {\"current_retail_price\", type number}, {\"tax_exempt_yn\", type text}, {\"promo_yn\", type text}, {\"new_product_yn\", type text}, {\"\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales by Store",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "transaction_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99042228-10d8-4d49-b097-871553252d7b",
            "sourceColumn": "transaction_id",
            "summarizeBy": "sum"
          },
          {
            "name": "transaction_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "52b42546-b7b7-4622-a8e9-5229ebe11e8a",
            "sourceColumn": "transaction_date",
            "summarizeBy": "none"
          },
          {
            "name": "transaction_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "f4fd9428-41ab-4c7d-b61c-41bae79d0657",
            "sourceColumn": "transaction_time",
            "summarizeBy": "none"
          },
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9e1f982-636b-4833-90d3-220fc8c1b9df",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "staff_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "851e2bdb-7885-4ef8-99f2-0582e73d2d31",
            "sourceColumn": "staff_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17866fc8-7af4-448b-8093-ee0cafdd034a",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "instore_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bcbddee-d27e-450a-b8c8-73663843ba8c",
            "sourceColumn": "instore_yn",
            "summarizeBy": "none"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71c8f127-5e5b-4aa9-a0b5-637c5739168b",
            "sourceColumn": "order",
            "summarizeBy": "sum"
          },
          {
            "name": "line_item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d84b058-4ed2-4566-a82b-dffd74e04124",
            "sourceColumn": "line_item_id",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9cb44dc1-a4f3-4bca-b7b7-fe73ede20266",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "quantity_sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e76be056-c154-4990-9308-ced217b7f591",
            "sourceColumn": "quantity_sold",
            "summarizeBy": "sum"
          },
          {
            "name": "unit_price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0e912c9c-41aa-4a4d-b21e-ddee0c96fbbd",
            "sourceColumn": "unit_price",
            "summarizeBy": "sum"
          },
          {
            "name": "promo_item_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09b25e56-7ded-4802-b72b-68a9a552a596",
            "sourceColumn": "promo_item_yn",
            "summarizeBy": "none"
          },
          {
            "name": "Time Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "FLOOR(",
              "    'Sales by Store'[transaction_time],",
              "    \"1:00\"    ",
              ")"
            ],
            "formatString": "Long Time",
            "lineageTag": "2aa98b79-54a3-471f-abf4-b27ab37ffc78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "expression": [
              "",
              "CURRENCY(",
              "    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "ead62b0f-f909-403e-8d83-d5857a1cdad2",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "c51e4495-fcba-4b2a-9b8c-1687e5845f50",
        "partitions": [
          {
            "name": "Sales by Store",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Sales by Store.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"transaction_id\", Int64.Type}, {\"transaction_date\", type date}, {\"transaction_time\", type time}, {\"store_id\", Int64.Type}, {\"staff_id\", Int64.Type}, {\"customer_id\", Int64.Type}, {\"instore_yn\", type text}, {\"order\", Int64.Type}, {\"line_item_id\", Int64.Type}, {\"product_id\", Int64.Type}, {\"quantity_sold\", Int64.Type}, {\"unit_price\", type number}, {\"promo_item_yn\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "store_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "55a48c95-0d35-47d9-b968-2c00c7293bbe",
            "sourceColumn": "store_id",
            "summarizeBy": "none"
          },
          {
            "name": "store_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bede19f-680e-411b-a3f9-d54cdf175dad",
            "sourceColumn": "store_type",
            "summarizeBy": "none"
          },
          {
            "name": "store_square_feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eaf6429c-a01e-41c3-870a-cf465713f89c",
            "sourceColumn": "store_square_feet",
            "summarizeBy": "sum"
          },
          {
            "name": "store_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ea19959-a259-4c83-8d33-2434caa0858f",
            "sourceColumn": "store_address",
            "summarizeBy": "none"
          },
          {
            "name": "store_city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3565cf7e-52ec-40ae-b153-622be3064f17",
            "sourceColumn": "store_city",
            "summarizeBy": "none"
          },
          {
            "name": "store_state_province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1792131b-6085-4309-a144-59835e886f1f",
            "sourceColumn": "store_state_province",
            "summarizeBy": "none"
          },
          {
            "name": "store_postal_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04889af7-3b83-4952-82c4-1fc8f4fe6da3",
            "sourceColumn": "store_postal_code",
            "summarizeBy": "sum"
          },
          {
            "name": "store_longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e967f605-713e-431d-94f8-1f73072d7593",
            "sourceColumn": "store_longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "store_latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f437936-e83b-47d7-96ad-a216b3bf69bb",
            "sourceColumn": "store_latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee4a7add-51a0-47ea-bc62-35b3c2ea87b7",
            "sourceColumn": "manager",
            "summarizeBy": "sum"
          },
          {
            "name": "Neighorhood",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e8ef1f0-0b8b-4dd4-a9ec-f444a7402709",
            "sourceColumn": "Neighorhood",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fe47f845-dfb9-4b8a-95bc-0994e2cb6886",
        "partitions": [
          {
            "name": "Store Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataSourceRoot & \"\\Store Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"store_id\", Int64.Type}, {\"store_type\", type text}, {\"store_square_feet\", Int64.Type}, {\"store_address\", type text}, {\"store_city\", type text}, {\"store_state_province\", type text}, {\"store_postal_code\", Int64.Type}, {\"store_longitude\", type number}, {\"store_latitude\", type number}, {\"manager\", Int64.Type}, {\"Neighorhood\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measures Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "de347450-0557-4571-ba9d-cef2f6c9c373",
        "measures": [
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "SUMX(",
              "    'Sales by Store',",
              "    'Sales by Store'[quantity_sold] *",
              "    RELATED(",
              "        'Product Lookup'[current_cost]",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "6a077332-e137-4b59-9fbf-7c87cb9c19f0"
          },
          {
            "name": "Customer Sales",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "SUMX(",
              "    'Sales by Store',",
              "    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a4070089-3026-4395-9ef8-149ff3109e18"
          },
          {
            "name": "Profit",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "[Customer Sales] - [Cost]"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "20e9e185-0d06-4b9f-8c1f-f5f013b002b5"
          },
          {
            "name": "Customer Sales (Last Year)",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    DATEADD(",
              "        'Calendar'[Transaction_Date],",
              "        -1,",
              "        YEAR",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3adde8cc-05d5-40a0-83db-aca15c96b357"
          },
          {
            "name": "Customer Sales Last Year (ISBLANK)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "        [Customer Sales (Last Year)]",
              "    ),",
              "    \"No Sales\",",
              "    [Customer Sales (Last Year)])"
            ],
            "lineageTag": "98ca2074-d67a-47f3-8337-ffca765cb5d4"
          },
          {
            "name": "Orders by Females",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "VAR TotalOrdersFemale =",
              "CALCULATE(",
              "    SUM(",
              "        'Food Inventory'[quantity_sold]",
              "    ),",
              "    FILTER(",
              "        'Customer Lookup',",
              "        'Customer Lookup'[gender] = \"F\"",
              "    )",
              ")",
              "RETURN",
              "TotalOrdersFemale"
            ],
            "lineageTag": "b27edb51-b1b8-42d7-9503-709976aa77c0"
          },
          {
            "name": "Order by Females (Wrong)",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "VAR TotalOrder  =",
              "SUM(",
              "    'Food Inventory'[quantity_sold]",
              ")",
              "RETURN",
              "CALCULATE(",
              "    TotalOrder,",
              "    FILTER(",
              "        'Customer Lookup',",
              "        'Customer Lookup'[gender] = \"F\"",
              "        )",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "07aa3ad2-67fc-43e7-91c7-30f04f1ecc84"
          },
          {
            "name": "% Quantity Sold by Females",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "VAR TotalOrdersFemale =",
              "CALCULATE(",
              "    SUM(",
              "        'Sales by Store'[quantity_sold]",
              "    ),",
              "    FILTER(",
              "        'Customer Lookup',",
              "        'Customer Lookup'[gender] = \"F\"",
              "    )",
              ")",
              "VAR QuantitySold =",
              "SUM(",
              "    'Sales by Store'[quantity_sold]",
              ")",
              "",
              "VAR Ratio =",
              "DIVIDE(",
              "    TotalOrdersFemale,",
              "    QuantitySold,",
              "    \"-\"",
              ")",
              "",
              "RETURN Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ab8ddb0-d63b-431f-b879-dec2937e6f7c"
          },
          {
            "name": "Total Customers",
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Customer Lookup'[customer_id]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f645b846-347b-4450-9b97-2a1165282e3a"
          },
          {
            "name": "Total Employess",
            "displayFolder": "Scalar Measures",
            "expression": [
              "",
              "COUNTROWS(",
              "    'Employee Lookup'",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0241a15f-32be-42fe-9c8a-35e4e5755bc6"
          },
          {
            "name": "Formatted Cost",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              " ROUND(",
              "    CURRENCY(",
              "        [Cost]",
              "    ),",
              "    2",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9a81d33a-6a25-461e-a467-0027b720a0d3"
          },
          {
            "name": "Formatted Customer Sales",
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "CURRENCY(",
              "    [Customer Sales]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a43fddda-3f6e-4f06-a6cb-63a5e7312996"
          },
          {
            "name": "Formatted Customer Sales (Last Year)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales By Store",
            "expression": [
              "",
              "VAR UnformattedData =",
              "COALESCE(",
              "    [Customer Sales (Last Year)],",
              "    \"-\"",
              ")",
              "",
              "RETURN UnformattedData"
            ],
            "lineageTag": "0634c649-1477-4828-a340-ed4124cbdac3"
          },
          {
            "name": "Store 3 Sales of Whole Beans & Teas",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    'Store Lookup'[store_id] = 3,",
              "    'Product Lookup'[product_group] = \"Whole Bean/Teas\"",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a64e636d-9253-44cf-ba82-f176e3267679"
          },
          {
            "name": "Store 3 Sales of Whole Beans & Teas (All Modifier)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    'Store Lookup'[store_id] = 3,",
              "    'Product Lookup'[product_group] = \"Whole Bean/Teas\",",
              "    ALL('Store Lookup')",
              ")"
            ],
            "lineageTag": "1f0f1209-0d65-420d-b9ae-0ab0711f86ba"
          },
          {
            "name": "Total Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    REMOVEFILTERS(",
              "        'Sales by Store'",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a131d870-f812-4464-8ea9-b398793c5364"
          },
          {
            "name": "Store 5 Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id]=5",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "fa7b99e8-e856-4641-9fa6-76ef90b889ea"
          },
          {
            "name": "Store 3 Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id] = 3",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "119726fd-eb9b-4576-88a9-20235b0fd55f"
          },
          {
            "name": "Store 8 Profit",
            "expression": [
              "",
              "CALCULATE(",
              "    [Profit],",
              "    KEEPFILTERS(",
              "        'Store Lookup'[store_id]= 8",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1a0b0466-44ef-45c1-980f-f4f9653608b2"
          },
          {
            "name": "% of Store Sales",
            "expression": [
              "",
              "VAR AllStoresSales=",
              "CALCULATE(",
              "    [Profit],",
              "    REMOVEFILTERS(",
              "        'Store Lookup'[store_id]",
              "    )",
              ")",
              "VAR PercentOfTotal=",
              "DIVIDE(",
              "    [Profit],",
              "    AllStoresSales",
              ")",
              "",
              "RETURN PercentOfTotal"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4f6c0fed-6e25-4886-976d-75b338253e18"
          },
          {
            "name": "Count of Product ID (Distinct)",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Product Lookup'[product_id]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1775af0a-3fec-44ee-a7f7-7dd64e608c02"
          },
          {
            "name": "Count of Product ID (Values)",
            "expression": [
              "",
              "COUNTROWS(",
              "    VALUES(",
              "        'Product Lookup'[product_id]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "723f15cf-95a2-4c3b-82d1-70abf4b92f1c"
          },
          {
            "name": "Retail Price (SELECTEDVALUE)",
            "expression": [
              "",
              "SELECTEDVALUE(",
              "    'Product Lookup'[current_retail_price]",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3fcbd3f4-3d5c-4e8a-b46e-48c6ad5d5799"
          },
          {
            "name": "Quantity Sold",
            "expression": [
              "",
              "DIVIDE(",
              "    [Customer Sales],",
              "    SELECTEDVALUE(",
              "        'Product Lookup'[current_retail_price]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a16b04b5-2bde-4641-b756-c6bb4faeaeef"
          },
          {
            "name": "Customer Sales (ALLEXCEPT)",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    ALLEXCEPT(",
              "        'Sales by Store',",
              "        'Product Lookup'[product_group],",
              "        'Calendar'[Transaction_Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c82cb63b-0a60-4636-b3c1-56212fc61279"
          },
          {
            "name": "Customer Sales (ALLEXCEPT Assignment)",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    ALLEXCEPT(",
              "        'Sales by Store',",
              "        'Calendar'[Transaction_Date],",
              "        'Store Lookup'[store_id],",
              "        'Customer Lookup'[customer_first-name],",
              "        'Product Lookup'[product_group]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "74b55c63-7c31-4dfc-954a-dd92c7624f64"
          },
          {
            "name": "% of Store-Level Sales",
            "expression": [
              "",
              "VAR StoreLevelSales =",
              "CALCULATE(",
              "    [Customer Sales],",
              "    REMOVEFILTERS('Customer Lookup'),",
              "    KEEPFILTERS('Calendar')",
              ")",
              "",
              "VAR Ratio =",
              "DIVIDE(",
              "    [Customer Sales (ALLEXCEPT Assignment)],",
              "    StoreLevelSales",
              ")",
              "",
              "RETURN Ratio",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "16d3c98d-8415-4667-9058-9ebd9f793001"
          },
          {
            "name": "Customer Sales (ALLSELECTED)",
            "expression": [
              "",
              "CALCULATE(",
              "    [Customer Sales],",
              "    ALLSELECTED(",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "9b41f416-37da-4408-86b6-d05ddeb25735"
          },
          {
            "name": "Total Sold",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "SUM(",
              "    'Food Inventory'[quantity_sold]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "46d46dc4-b8c9-42a0-8e12-dcecb09e3cc5"
          },
          {
            "name": "Total Baked",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "SUM(",
              "    'Food Inventory'[quantity_start_of_day]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3f95174e-502e-4e1c-acdc-5a559794b003"
          },
          {
            "name": "% of Total Baked",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "VAR SelectedTotalBaked =",
              "CALCULATE(",
              "    [Total Baked],",
              "    ALLSELECTED(",
              "    )",
              ")",
              "VAR Ratio=",
              "DIVIDE(",
              "    [Total Baked],",
              "    SelectedTotalBaked",
              ")",
              "",
              "RETURN Ratio"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d034d4e5-c200-4f8e-885d-3749e714aa84"
          },
          {
            "name": "% of Total Sold",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "VAR SelectedTotalSold =",
              "CALCULATE(",
              "    [Total Sold],",
              "    ALLSELECTED(",
              "    )",
              ")",
              "VAR Ratio=",
              "DIVIDE(",
              "    [Total Sold],",
              "    SelectedTotalSold",
              ")",
              "",
              "RETURN Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f2759154-f3a3-4ddd-afb1-ad9e2f025680"
          },
          {
            "name": "% of All Baked",
            "displayFolder": "Food Inventory",
            "expression": [
              "",
              "VAR AllBaked=",
              "CALCULATE(",
              "    [Total Baked],",
              "    REMOVEFILTERS(",
              "        'Food Inventory'",
              "    )",
              ")",
              "",
              "VAR Ratio =",
              "DIVIDE(",
              "    [Total Baked],",
              "    AllBaked",
              ")",
              "",
              "RETURN Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a724dffc-5ff4-4096-9d7b-c38cbf4fbea2"
          }
        ],
        "partitions": [
          {
            "name": "Measures Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCk7MLchJVdJRUoqNBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column2\", \"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Distinct Example",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c3312d7a022b4b64b08db3c3afcca5fa"
          }
        ],
        "columns": [
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d5ef69f4-ad6a-4bd4-975c-7fd0018598f2",
            "sourceColumn": "Product Lookup[product_group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "0d1ba765-abfc-43b6-b580-418262846cad",
        "partitions": [
          {
            "name": "Distinct Example",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DISTINCT(",
                "    'Product Lookup'[product_group]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Values Example",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7ccf35783cb44652a574874c63499641"
          }
        ],
        "columns": [
          {
            "name": "product_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5c050c55-1b9d-4acf-b95c-9b0008cbdd19",
            "sourceColumn": "Product Lookup[product_group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f41dff0f-d6a0-4eda-b101-214cfa906349",
        "partitions": [
          {
            "name": "Values Example",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VALUES(",
                "    'Product Lookup'[product_group]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SELECTCOLUMNS Demo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2810f5fb020c4033b3c3a8cecdd9b999"
          }
        ],
        "columns": [
          {
            "name": "Employee ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bea8c165-79ab-47d6-b6e3-c47e4f298fea",
            "sourceColumn": "[Employee ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mananger Name & Store",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b87715b3-9cfc-4924-9fa4-dcb93477bdb9",
            "sourceColumn": "[Mananger Name & Store]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "464c379d-b3c9-4f07-a4b3-61f7f026e69e",
        "partitions": [
          {
            "name": "SELECTCOLUMNS Demo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    FILTER(",
                "        'Employee Lookup',",
                "        'Employee Lookup'[staff_id] IN {6,16,31}",
                "    ),",
                "    \"Employee ID\",",
                "    'Employee Lookup'[staff_id],",
                "    \"Mananger Name & Store\",",
                "    'Employee Lookup'[first_name] & \" \" & 'Employee Lookup'[last_name] & \"-\" & 'Employee Lookup'[location]",
                "",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}