table 'Employee Lookup'
	lineageTag: 3df49bda-9e6a-4be3-80eb-7c40de5d67d3

	column staff_id
		dataType: int64
		isKey
		formatString: 0
		lineageTag: e62d8c75-aa85-4fe3-af44-60a730d13412
		summarizeBy: none
		sourceColumn: staff_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: f3f19ffe-7d15-4b38-a64e-8cc3b4c3bb1f
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: e45abae4-4858-4375-808c-f05a5e8bfdf3
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: 9ccaef00-44d1-4a6d-bb2c-20a304a8c6d4
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7b26b9cc-a667-49e3-8fac-3fa55289f670
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column location
		dataType: string
		lineageTag: 876c71cb-0f13-4af7-9cf3-a2250063ca88
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	partition 'Employee Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\PowerBI\Advanced Dax Course\Development\dax-studies\raw_data\Employee Lookup.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"staff_id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"position", type text}, {"start_date", type date}, {"location", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

