table 'Food Inventory'
	lineageTag: fe650e26-b166-4651-8dc4-dfe7a425020e

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: dc415708-95d0-4ead-b638-bcaff45c6a23
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column baked_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 16be5c30-8cba-4939-a2c9-e1050d37a3f3
		summarizeBy: none
		sourceColumn: baked_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bf4912f1-5dca-4a68-9611-b51d63e2dd60
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 3cec197a-8618-4c65-81db-d53608fb14d6
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity_start_of_day
		dataType: int64
		formatString: 0
		lineageTag: 4eac2a49-3e7b-4c92-88a0-44cf4e20dd56
		summarizeBy: sum
		sourceColumn: quantity_start_of_day

		annotation SummarizationSetBy = Automatic

	column quantity_sold
		dataType: int64
		formatString: 0
		lineageTag: 755ed061-b554-41e7-9295-e897ff9f8d17
		summarizeBy: sum
		sourceColumn: quantity_sold

		annotation SummarizationSetBy = Automatic

	partition 'Food Inventory' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\PowerBI\Advanced Dax Course\Development\dax-studies\raw_data\Food Inventory.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"baked_date", type date}, {"transaction_date", type date}, {"product_id", Int64.Type}, {"quantity_start_of_day", Int64.Type}, {"quantity_sold", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

