table 'Sales by Store'
	lineageTag: c51e4495-fcba-4b2a-9b8c-1687e5845f50

	column transaction_id
		dataType: int64
		formatString: 0
		lineageTag: 99042228-10d8-4d49-b097-871553252d7b
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 52b42546-b7b7-4622-a8e9-5229ebe11e8a
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: f4fd9428-41ab-4c7d-b61c-41bae79d0657
		summarizeBy: none
		sourceColumn: transaction_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: c9e1f982-636b-4833-90d3-220fc8c1b9df
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column staff_id
		dataType: int64
		formatString: 0
		lineageTag: 851e2bdb-7885-4ef8-99f2-0582e73d2d31
		summarizeBy: none
		sourceColumn: staff_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 17866fc8-7af4-448b-8093-ee0cafdd034a
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column instore_yn
		dataType: string
		lineageTag: 8bcbddee-d27e-450a-b8c8-73663843ba8c
		summarizeBy: none
		sourceColumn: instore_yn

		annotation SummarizationSetBy = Automatic

	column order
		dataType: int64
		formatString: 0
		lineageTag: 71c8f127-5e5b-4aa9-a0b5-637c5739168b
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column line_item_id
		dataType: int64
		formatString: 0
		lineageTag: 1d84b058-4ed2-4566-a82b-dffd74e04124
		summarizeBy: sum
		sourceColumn: line_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 9cb44dc1-a4f3-4bca-b7b7-fe73ede20266
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity_sold
		dataType: int64
		formatString: 0
		lineageTag: e76be056-c154-4990-9308-ced217b7f591
		summarizeBy: sum
		sourceColumn: quantity_sold

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 0e912c9c-41aa-4a4d-b21e-ddee0c96fbbd
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promo_item_yn
		dataType: string
		lineageTag: 09b25e56-7ded-4802-b72b-68a9a552a596
		summarizeBy: none
		sourceColumn: promo_item_yn

		annotation SummarizationSetBy = Automatic

	column 'Time Group' = ```
			
			FLOOR(
			    'Sales by Store'[transaction_time],
			    "1:00"    
			)
			```
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2aa98b79-54a3-471f-abf4-b27ab37ffc78
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Total Revenue' =
			
			CURRENCY(
			    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ead62b0f-f909-403e-8d83-d5857a1cdad2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Sales by Store' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\PowerBI\Advanced Dax Course\Development\dax-studies\raw_data\Sales by Store.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"transaction_id", Int64.Type}, {"transaction_date", type date}, {"transaction_time", type time}, {"store_id", Int64.Type}, {"staff_id", Int64.Type}, {"customer_id", Int64.Type}, {"instore_yn", type text}, {"order", Int64.Type}, {"line_item_id", Int64.Type}, {"product_id", Int64.Type}, {"quantity_sold", Int64.Type}, {"unit_price", type number}, {"promo_item_yn", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

